### ISSUE TITLE
Hot module replacement

### ISSUE THREAD

**Issue by bjrmatos** [substack/node-browserify#1143]
Hi, are there any plans to support this feature? (Something like [webpack does](http://webpack.github.io/docs/hot-module-replacement.html))

I think it will allow some good tools to be created on top of it, like [react-hot-loader](https://github.com/gaearon/react-hot-loader)

**Comment by mattdesl** [comment]
I have been poking around in this area lately. It would be cool if browserify exposed some features which made this possible, but it does seem like a [rabbit hole of complexity](https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack).

It's worth mentioning some other ways of tackling the problem that don't involve major changes to browserify:

#### specific tooling

Often you just want to apply hot-loading to a specific area of frontend development, eg. animations, render loops, UI layout, CSS changes, etc. In some cases a custom tool can provide the best experience and give you full control over file watching and how updates are triggered. 

For example:

- [glslify-live](https://github.com/hughsk/glslify-live) for hot reloading GLSL shaders
- [json-live](https://github.com/mattdesl/json-live) for hot reloading JSON data
- [LiveReload](http://livereload.com/) for hot reloading CSS, can be used with gulp, grunt, [wtch](https://github.com/mattdesl/wtch), [budo](https://github.com/mattdesl/budo), etc

The json-live and glslify-live approach (chokidar server + transform + sse-stream) could be applied to other areas like template updates and app-specific UI development. It might be worth building these tools on some shared set of modules that deal with sse-stream et al.

#### Remote Debugging

This is something @caspervonb and I have been looking at as well. Browserify or watchify can be used as per normal, but the updated source is then sent to Chrome's Remote Debugging interface which tells V8 to handle the diffing and code updating.  This has a couple benefits over evals, like better handling of IIFEs, but also has some [major drawbacks](https://code.google.com/p/v8/issues/detail?id=3894&q=liveedit&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Area%20Stars) and is currently limited to Chrome.

- [budo-chrome](https://github.com/mattdesl/budo-chrome)
- [amok](https://github.com/caspervonb/amok)

**Comment by caspervonb** [comment]
For code, it just doesn't seem viable to do it without involving the debugger, I've spent quite a-lot of time trying to come up with an alternative to using a debugging connection because it would make the implementation runtime agnostic, eval hacking, prototype substitution, while you can do patching of some-things, there's a clear difference between re-compiling your code through a debug session and re-evaluating your code/data through hot replacements, essentially it is edit and continue.

So basically, the differences are re-compiling via a debugging session lets you modify any code and continue afterwards, including anonymous closures, side effects will not be run since there is no code evaluation/execution.

Hot module replacements on the other hand seem to be more about data, a module in webpack doesn't have to code, seems like it almost acts like an asset loader, react-hot-loader for example executes side effects and patches up prototypes, so it's a different kind of feature, and they could quite easily co-exist.

Feel free to correct me If I'm totally uninformed about webpack

**Comment by augbog** [comment]
There was an issue filed in https://github.com/gaearon/react-hot-loader/issues/61 about how they leverage HMR in webpack. Would also love to see HMR in Browserify if possible.

**Comment by slorber** [comment]
+1

**Comment by bjrmatos** [comment]
I think this is a nice feature that browserify should support or at least provide a basis to implement a plugin

**Comment by milankinen** [comment]
Actually, hot reloading is now possible with Browserify too (uses same react-hot-api): https://github.com/milankinen/livereactload

**Comment by bjrmatos** [comment]
@milankinen is only react the unique use case? or is generic for js modules?

**Comment by milankinen** [comment]
@bjrmatos In theory this is a generic implementation. However in practice, only React programming practices won't produce "hidden state" to the page (in DOM for example). But if you can keep your modules stateless (or at least store state to the React Component's state) then you can modify whatever in your module and it'll rock!

You can take look at the fourth example to see how custom state management can be done with LiveReactload (actually, I prefer to use that model in my personal projects and the demo video has same idea behind).

**Comment by bjrmatos** [comment]
great job @milankinen ! will try to play with livereactload soon!, I would like to hear what @substack has to say about this

**Comment by gabssnake** [comment]
https://github.com/milankinen/livereactload Looks promising!

**Comment by substack** [comment]
I investigated a more general approach (more general than HMR) 2 months ago and got something working, at least for simple use cases ([live-patch](https://github.com/substack/live-patch)):

![live patch](https://raw.githubusercontent.com/substack/live-patch/master/example/demo.gif)

However this implementation is very fragile and I haven't been able to get it working for arbitrary bundles yet.
I wrote the first half of this implementation after listening to @jeresig give a talk at empirejs 2 years ago about live reloading wizardry they do for kahn academy's educational programming tool.

**Comment by gaearon** [comment]
>For some kinds of updates you'll always need to re-run a bunch of side effects where you're probably better off reloading the entire page

The neat thing is, if you provide an opt-in API for modules to tell how to run those side effects, then we can run build transforms for things we *know* how to update (e.g. React components, CSS, Flux Stores, etc). If it works in 80% of cases it's already good enough, and makes the common workflow a *lot* better.

So I'd say it's not the surgical diffs that Browserify needs to support—it's a way for individual modules to say how they want to be updated. Which is pretty much what Webpack's HMR is.

**Comment by gaearon** [comment]
>For more details: LiveReactload does not reload single modules but the whole bundle instead. Reloading injections are done with a custom transform function that

This is a big problem with LiveReactload and the reason people are bumping into many issues with it. It's just much more error prone to reload the whole application code instead of a few changed modules. That's why HMR model is more stable in my opinion and works more reliably across different apps.

**Comment by tcurdt** [comment]
While it's great how well the HMR model works I am wondering whether reloading the whole thing isn't the better approach for React (at least). It would force one to write stateless components and all that needs to be re-injected on a reload is the state. It feels much more KISS.

That said I wouldn't mind if one could port the HMR to browserify :)

**Comment by Kureev** [comment]
I'm not saying I've solved this issue, but you can check out my [`browserify-patch-server` implementation](https://github.com/Kureev/browserify-patch-server) (you'll get pretty messages about state and changes of your bundle(s)), and [`react-live` implementation over it](https://github.com/Kureev/browserify-react-live). 

Interaction between client and server based on `diff`s: server calculate `diff` between old file content and updated file content and then broadcast it to all clients via WebSockets. Client I wrote for `react` applies  patch to bundle in the runtime and achieve a nice experience of live-patching.

Of course, it doesn't solve **all** existing problems, but I hope it's a step in a right direction. I wonder what @substack thinks about it.

**Comment by AgentME** [comment]
It seems like the previous Browserify solutions posted have been specific to React or just not as general as Webpack's HMR API.

I've just made [browserify-hmr](https://github.com/AgentME/browserify-hmr), which is a Browserify plugin that fully implements Webpack's Hot Module Replacement API. There's probably a pile bugs still in there and the code isn't terribly well organized yet, but it seems to show that a plugin strategy works well enough. It currently lacks a ready-to-use compatible websocket solution so that it can avoid polling and lacks a compatible react-hot-loader-like transform for one's React needs.

**Comment by Kureev** [comment]
@AgentME Can't agree with you: if you'll take a look on mine `browserify-patch-server`, you wouldn't see anything about React. It's just a server that emits messages with diffs for specific changed files. But I don't have a goal to suit webpack's HMR API, that's true. From my point of view you don't need to replace whole file (module) if you've changed only 1 line.

But I think it'll be handy for a plenty people to be able to use webpack's plugins based on HMR in BF also :+1:

**Comment by caspervonb** [comment]
Amok now comes with Amokify (though rough and not yet stable) which you can [read about more here] (https://medium.com/@caspervonb/amokify-and-an-interactive-programming-workflow-11f863aca2d0)

> It seems like the previous Browserify solutions posted have been specific to React or just not as general as Webpack's HMR API.

Also false for Amok, it's does nothing framework specific at all.

**Comment by substack** [comment]
Closing this issue since there are lots of great options now: amok, browserify-hmr, livereactload.
