### ISSUE TITLE
browserify command doing nothing

### ISSUE THREAD

**Issue by sambws** [substack/node-browserify#1154]
hi! i'm running ubuntu, and i'm looking to use browserify in accordance with teacup.js. after i installed browserify with npm, however, the ```browserify``` command didn't seem to do anything. this could just be me being new to linux and not knowing how to resolve issues, but i couldn't find any help fitting this description elsewhere. the commands i'm trying to run look like this-

```sam@sam-AY747AA-ABA-p6310y:/usr/local/lib/node_modules/browserify/example/api/browser$ browserify main.js -o bundle.js
sam@sam-AY747AA-ABA-p6310y:/usr/local/lib/node_modules/browserify/example/api/browser$ ```

as you can see, after trying to execute the command, it simply took me back to the neutral terminal command. if i could get any tips on fixing this, that would be great!

**Comment by substack** [comment]
This is normal. It is the [rule of silence](http://www.faqs.org/docs/artu/ch01s06.html#id2878450): when a program has nothing interesting or surprising to say, it should say nothing.

Since you told browserify to write output to `bundle.js`, the `bundle.js` now contains the bundle of javascript. You can put a `<script src="bundle.js"></script>` tag in some html now.

**Comment by sambws** [comment]
@substack bundle.js was never created when i ran that command, unless it's supposed to be somewhere else other than the folder where i ran it?

**Comment by wreardan** [comment]
I'm having this same problem.  It does absolutely nothing on my Linux Server, but works totally fine on my Windows machine.  I tried downgrading Browserify on the Linux system to the version my Windows laptop is running but this did not solve the issue: help!
