### ISSUE TITLE
Requiring standalone bundle generated by browserify --s within browserify project

### ISSUE THREAD

**Issue by iamcdonald** [substack/node-browserify#1197]
So, I've created a library that I decided to package up using browserify --s in order to create a UMD shimmed module and all is good.

However, while the shim allows it to be loaded in a bunch of different scenarios (CommonJS, AMD, Window) it appears it cannot be consumed within another browserify project.

My hunch is that running browserify simply follows requires all the way down when bundling rather than taking into account the nesting 'require' contexts that seems to be handled by the https://github.com/substack/browser-pack/blob/master/prelude.js in the generated library bundle. Thus when it get's inside the library it looks for files required inside it and expects them to be within the consuming project due to the path provided.

I guess I'm wondering if this is a bug or if I'm doing something wrong?
Any pointers would be appreciated, thanks.

**Comment by jmm** [comment]
@iamcdonald Thanks for the report. You're not doing anything wrong. This is a known issue that's being discussed in https://github.com/substack/node-browserify/pull/1151. I also list current workarounds there. For the purpose of distributing a browserified library that you wish to be consumable by browserify, currently you should run it through derequire or minify it. I'm closing this issue since it's already being discussed in #1151, so feel free to contribute feedback there.
