### ISSUE TITLE
CLI path resolution inconsistent for entry files and -e|--entry vs. -r|--require

### ISSUE THREAD

**Issue by jmm** [substack/node-browserify#1219]
In browserify 9.0.8 CLI on linux path arguments are resolved inconsistently for entry files / `-e` / `--entry` vs `-r` / `--required`.  Seems counterintuitive. Is there a reason to resolve them differently? Note: triggering it doesn't require an `expose` argument for the `-r` files.

```
# Module files a.js and b.js

# Error: Cannot find module 'b'
browserify a -r b
browserify -e a -r b

# No error, both bundled
browserify a -r ./b
browserify -e a -r ./b
```

**Comment by terinjokes** [comment]
I believe `entry` is really expected to be a file, whereas `require` is documented as being anything that can be resolved by the node require resolution. I'm not aware of any history for them doing different things.

That said, this is method is kinda gnarly, and I should really take some time to clean it up.

**Comment by jmm** [comment]
@terinjokes Thanks for the reply. I'm not sure I see the distinction -- shouldn't they both just be resolved to a module file starting from some base dir (the same one in the case of these examples)? Unless there's a good reason to do otherwise it seems like it would be ideal for them to perform consistently in terms of the input they can take and how they resolve it to a file. No?

**Comment by terinjokes** [comment]
@jmm I was hoping our mysterious leader would come by and comment about why they do different things. :wink:

**Comment by jmm** [comment]
@terinjokes Ah, got it, sounds good.

**Comment by substack** [comment]
`--require` looks up files the `require.resolve()` way because that's what `require()` does.

`--entry` expects file paths like `fs.createReadStream()` would

It's difficult to do both operations in a single step. Sometimes you can `require()` a path but other times you can only `fs.createReadStream()` a path. Sometimes you can do both and sometimes neither one can work. When you do both, it's possible to have 2 different outcomes.

If you have these files:

* whatever.js
* node_modules/whatever.js/index.js

Then the string `"whatever.js"` passed to either option will give back different results.

**Comment by jmm** [comment]
Thanks for explaining that @substack. I see what you guys mean, and that totally makes sense if the 80% case for `-e|--entry` is files outside of `node_modules`, and the opposite is the case for `-r|--require`. I don't know why I was so confused on this, even through your explanation @terinjokes.
