### ISSUE TITLE
 Make the 'require' keyword configurable

### ISSUE THREAD

**Issue by turristan** [substack/node-browserify#1254]
[`nwjs`](http://nwjs.io) lets you call all Node.js modules directly from DOM. 

Personally,  I'd like to build a `nwjs` application and `browserify` is certainly in the toolbox. However, the question is the `require` keyword. `Browserify` hijacked it. Then there will be no way to access `nwjs` api.

So we make the `require` keyword configurable? `require` should be the default one, but we can override it with `include`, `import`, `use` and etc.

Maybe I missed anything in the docs, or there is another way, please let me know.

Thank you

Yours sincerely.

**Comment by jmm** [comment]
You're saying you'd like to be able to configure browserify so that it resolves calls like `include()|import()|whatever()` instead of `require()`? Can you please take a look at #624 and see if it has any bearing on your situation? Does nwjs provide a global `require()` that would allow you to `b.exclude()` the things you want to access from it when you create your bundle?

**Comment by turristan** [comment]
Thank you for your kind help.

This should help. `nwjs` does provide a global `require`. So all I'm gonna do is simply exclude all the required core node modules.

Seriously it is not that neat.
I still hold my opinion. But you're the boss.

Regards..

**Comment by jmm** [comment]
@turristan You're welcome.

> So all I'm gonna do is simply exclude all the required core node modules.

So is this just about the core node modules? If I could give you a neat way to exclude all of those would that improve the situation?

**Comment by turristan** [comment]
@jmm Guess so,  but browserify ain't gonna need it. Since browserify targets at browser land, and node-webkit is no way a real browserify, don't try to risk messing things up. 

If you agree so, just close the issue.

Thanks.

**Comment by jmm** [comment]
@turristan Unfortunately I don't fully understand your situation. I'd say try this if you want:

```js
browserify({builtins: false})
```

I'm going to close the issue because this is my best suggestion with the information available and you seem satisfied with the resolution, but if you're still having a problem feel free to open a new issue with more information.
