### ISSUE TITLE
BOM not removed when file contains "global"

### ISSUE THREAD

**Issue by rigdern** [substack/node-browserify#1263]
### Impact

BOM doesn't get removed when a file uses the variable `global` resulting in an exception in the browser when attempting to use the script.

This is probably also the cause of #1095.

### Repro Steps

1. Download repro.zip from http://1drv.ms/1RCmzWb and unzip it
2. Run `npm install`
3. Run `browserify index.js -o bundle.js`
4. Open index.html in Chrome

**Unexpected result:** The Chrome console shows this error: `Uncaught SyntaxError: Unexpected token ILLEGAL` due to a BOM

**Expected**: "Success" is printed in the console.

**Comment by zertosh** [comment]
@rigdern Can you publish the repro case as a public repo? I don't have a microsoft account.

**Comment by rigdern** [comment]
@zertosh You should be able to use that link to download the file without signing in. Once the page is fully loaded, It'll show you the file and you can right-click on it and choose "Download". If that still doesn't work for you, I'll publish it as a git repo later today.

**Comment by zertosh** [comment]
In the future please try to create repos for issues - it's much easier to just clone than to go through the download process, unzipping, etc. – anyway, yeah, I see the issue and it's because the globals wrapper is added before the BOM stripping, so when it's time to remove the BOM, it's no longer the first char.

@jmm @substack I think it makes sense to move the BOM stripping into module-deps, as soon as the file is read - before any transforms or anything. thoughts?

**Comment by jmm** [comment]
@zertosh
> I think it makes sense to move the BOM stripping into module-deps, as soon as the file is read - before any transforms or anything. thoughts?

I should probably think it through more, but my initial reaction is that something like that sounds good. I actually ran into that on #1151 -- I added BOM detection to the pragma detection. Whereas if it worked the way you propose, that wouldn't have been necessary. Also, is there such a thing as a valid JSON file with a BOM? If so, that would currently also be borked because `json` comes before `unbom`. Is there any good use case for pushing a row or setting `row.source` to something that may contain a BOM between module-deps and `unbom` (that would outweigh having to strip BOMs yourself when doing so)?

Does everything go through the global transform? I wonder if module-deps should be responsible for changing the source in any way directly. Since `unbom`'ing currently takes place in browserify, maybe it makes sense to keep it there. If everything goes through the global transform it could happen there, right? (That wouldn't have helped me in the pragma situation though, but I guess that's a pretty special case.)

Is the BOM sequence valid or meaningful anywhere other than the start of a file? Could occurences of it anywhere in `row.source` just be stripped?

(I'm somewhat thinking out loud here.)

**Comment by zertosh** [comment]
> Also, is there such a thing as a valid JSON file with a BOM? If so, that would currently also be borked because json comes before unbom.

wow yeah, good call!

>  Is there any good use case for pushing a row or setting row.source to something that may contain a BOM between module-deps and unbom (that would outweigh having to strip BOMs yourself when doing so)?

None that I can think of. In fact, acorn marks them as [skippable](https://github.com/marijnh/acorn/blob/f1836381763148a3e90f48de1883d6e96607efbd/src/tokenize.js#L176) [nonASCIIWhitespace](https://github.com/marijnh/acorn/blob/baa833d6359ace7a98eb0830062b85f759457689/src/whitespace.js#L11). 

> Does everything go through the global transform? I wonder if module-deps should be responsible for changing the source in any way directly. Since unbom'ing currently takes place in browserify, maybe it makes sense to keep it there. If everything goes through the global transform it could happen there, right? 

Yeah, unless you use `noParse` or `detectGlobals: false`. I think it makes sense strip it [here](https://github.com/substack/module-deps/blob/e0e85fa49b564400c7517fc5ba892cf431d53405/index.js#L193) and [somewhere around here](https://github.com/substack/module-deps/blob/e0e85fa49b564400c7517fc5ba892cf431d53405/index.js#L86-L91). That way it's been stripped before any transform sees it, and it covers the cases where a row has an existing source or if module-deps read the source itself.

**Comment by jmm** [comment]
> None that I can think of. In fact, acorn marks them as skippable nonASCIIWhitespace.

Ok, thanks. So I think this comment was more in reference to this question, right?:

> Is the BOM sequence valid or meaningful anywhere other than the start of a file? Could occurences of it anywhere in row.source just be stripped?

My other question was asking if there are any good use cases we know of for pushing a new row following module-deps, say by a plugin that pushes a stream that comes after module-deps but before `unbom`, where that `row.source` could contain BOM.

> Yeah, unless you use `noParse` or `detectGlobals: false`. I think it makes sense strip it here and somewhere around here. That way it's been stripped before any transform sees it, and it covers the cases where a row has an existing source or if module-deps read the source itself.

Ok, thanks. Can you think of a situation where it would matter to a transform? If not then I think it can be handled by just moving `unbom` after `deps` and stripping them from source anywhere and everywhere. I'm basing that on [Q: What should I do with U+FEFF in the middle of a file?](http://unicode.org/faq/utf_bom.html#bom6) and what the [ES6 draft](https://people.mozilla.org/~jorendorff/es6-draft.html) has to say about it (search for `FEFF`). I don't know of any good reason for that character to be included literally for any other reason than as a BOM.

**Comment by zertosh** [comment]
> My other question was asking if there are any good use cases we know of for pushing a new row following module-deps, say by a plugin that pushes a stream that comes after module-deps but before unbom, where that row.source could contain BOM.

Not that I can think of. 

> Can you think of a situation where it would matter to a transform? If not then I think it can be handled by just moving unbom after deps and stripping them from source anywhere and everywhere. 

hmm, what if it's part of a string literal? maybe you want that there? The safest thing to do is to switch up the order of "json" and "unbom", and tweak insert-module-deps to also unbom. It already does its [own unshebang](https://github.com/substack/insert-module-globals/blob/68ec279f6365bfe34a37ef5136ebfeec3f7794a1/index.js#L58), so unboming is not without some precedent. Sound good?

**Comment by jmm** [comment]
@zertosh 
> hmm, what if it's part of a string literal? maybe you want that there?

I considered that, and ordinarily I'm very conservative about that sort of thing, but I think BOM is a very special case where I'd feel comfortable saying there's no "valid" reason to have that literal character in the source anywhere / for any reason other than as a BOM. And if it were, would that not just cause the problem reported in this issue?

> The safest thing to do is to switch up the order of "json" and "unbom"

Yes, this should happen if `unbom` continues to exist.

> and tweak insert-module-deps to also unbom. It already does its own unshebang, so unboming is not without some precedent. Sound good?

insert-module-globals right? I just took a quick look at that. I think if the logic would be duplicated in more than one place maybe there should just be a module, let's call it `unprefix` , that strips BOM and shebang and is called from both places (insert-module-globals and `unprefix` phase). But I think it'd be even better if it could only happen one time in one place. I don't think it's a good idea for module-deps to alter source directly, but maybe something should be added to it that browserify (or whatever consumer) can use to apply an unequivocal source transformation before the regular transforms. Or should a regular transform be able to tell that the file had a shebang line?

**Comment by zertosh** [comment]
A regular transform should be able to tell. Babel removes them for example. I don't mind if insert-module-globals does its own thing since it's a transform.

I also just noticed that insert-module-deps replaces the shebang with a `\n`, which makes sense to preserve the line numbers. This is specially important if your file already has a source map. But the unshebang step does not leave a `\n` behind, so if the file has a sourcemap and a shebang, there goes the line ordering.

**Comment by jmm** [comment]
> I also just noticed that insert-module-deps replaces the shebang with a \n, which makes sense to preserve the line numbers.

Yeah, that makes sense to propagate to `unshebang`.

So the pipeline may as well go `unbom > unshebang > json` I would think. Accompanied by a new major version.

**Comment by zertosh** [comment]
@rigdern If you update your browserify, it'll pull in insert-module-deps@6.4.3, which fixes the bug.

@jmm I'll :+1: that PR :smile:

**Comment by rigdern** [comment]
@zertosh Awesome, it worked. Thanks for fixing this so quickly!
