### ISSUE TITLE
Add `root` as an alias of `global`

### ISSUE THREAD

**Issue by jdalton** [substack/node-browserify#1272]
The recent version of lodash (v3.9.0) left some `root` vars in place in their node package. This works in node/io.js because `root === global`. Would you all be against adding `root` as an alias of `global`?

Related to https://github.com/lodash/lodash/issues/1218.

**Comment by jmm** [comment]
My two cents is that I'm not crazy about the idea of special-casing support for something from another project that they don't even want to document there (which is my understanding [[apparently there's also `GLOBAL`](https://github.com/joyent/node/pull/8156)]). Especially if it's an old legacy thing that people have had plenty of time and warning to stop doing (?). I'm open to the idea that perhaps this is a *really* special case though. I wonder how prevalent usage of the `root` variable is, particularly in npm packages. I'm guessing not that prevalent since I can't find another issue about it here.

**Comment by substack** [comment]
I've never heard of node defining `root` before either. I don't think it's good to support this if it's undocumented and rare, especially because `global` already triggers special cases that people are surprised by.

I don't see any mention of `root` in this list: https://nodejs.org/api/globals.html

**Comment by jdalton** [comment]
Yap, it's tricky for sure. I've modified lodash's unit tests to poison the global `root` value to avoid this kind of issue in the future.
