### ISSUE TITLE
Using a non-CommonJS module with CommonJS dependencies

### ISSUE THREAD

**Issue by wordempire** [substack/node-browserify#1301]
I am having quite some trouble getting a bower project that is hosted on npm to integrate properly in my workflow. Specifically, this project is built using bower as a dependency manager, and supports both AMD and browser globals.

Point in case is that I already have the dependies of this project working properly in browserify (namely, `Backbone` and `underscore`), so if possible, I would like to not have a duplicate of these dependencies. Is there any proper way to meet these requirements in browserify?

**Comment by substack** [comment]
I think the best way to fix this kind of issue is to get the upstream dependency to use UMD instead of just AMD or browser globals. Then the upstream UMD package can use `require()` to load underscore and Backbone. You could fix this with lots of hacks from browserify's API, but you will just end up with a brittle solution.

Hacking a library to support UMD is mostly straight forward. You can add an extra 

```
if (typeof define !== 'undefined') {
  // AMD
  // ...
} else if (typeof module !== 'undefined' && typeof exports !== 'undefined') {
  // commonjs
  var _ = require('underscore')
  var Backbone = require('backbone')
  module.exports = Whatever
} else {
  // browser global
  var _ = window._
  var Backbone = window.Backbone
  window.Whatever = Whatever
}
```
