### ISSUE TITLE
browserify (+ babelify): it is impossible to share code

### ISSUE THREAD

**Issue by gaydenko** [substack/node-browserify#1357]
Hi!

In a word: how to share lib between browserify/babelify projects?
At the moment I have:
```
prj1
  node_modules
    lib (symlink to share/lib)
  src (es6 files are here)
  package.json
  gulpfile.js
prj2
  node_modules
    lib (symlink to share/lib)
  src (es6 files are here)
  package.json
  gulpfile.js
share
  lib
     package.json
     shared es6.js files
```
Here share/lib/package.json is just:
```json
{
  "browserify": {
    "transform": ["babelify"]
  }
}
```
The aim is to share share/lib/*.js between prj1 and prj2. With the aim I have added symlinks to share/lib/ from prjN/node_modules/lib directories. But modules can not be found.

Where is my mistake?

P.S. Was not lucky to get an answer on SO, the last hope is here :)

**Comment by mattdesl** [comment]
Instead of symlinking to a shared folder, you should just use regular modules to share code between projects.

```js
import { someFunction } from 'my-shared-module'
console.log(someFunction())
```

Where `my-shared-module` folder structure looks like this, and uses babelify in its package.json browserify transform:

```
my-shared-module
  package.json
  shared es6.js files
```

Then, from your project folder, you can `npm link ../my-shared-module` to symlink it properly as a module during development. Once the shared code is stable, you can `npm install --save my-shared-module` instead of linking it.

https://docs.npmjs.com/cli/link  
http://justjs.com/posts/npm-link-developing-your-own-npm-modules-without-tears

**Comment by gaydenko** [comment]
Thanks, will play with `npm link`.
