### ISSUE TITLE
standalone xx   amd has problem    

### ISSUE THREAD

**Issue by zhoujianlin8** [substack/node-browserify#1431]
in module umd    'typeof define===\"function\"&&define.amd){define([],f)}'   

maybe  'typeof define===\"function\"&&define.amd){define('defineNamespace',[],f)}'

**Comment by zhoujianlin8** [comment]
and  how i can set  prelude  to fix

**Comment by jamie-pate** [comment]
The docs say that --standalone [module_name] will name the module, but as shown in this issue, that is not the case. AMD (at least requireJS) supports the module name as the first parameter to define, which was the expected output for me. Should I just report a new issue or was this closed without comment because the intent was unclear?
