### ISSUE TITLE
Builtins create hidden dependency on Browserify version

### ISSUE THREAD

**Issue by PatrickKing** [substack/node-browserify#1454]
I spent most of today teasing out why my webapp bundle was buggy only on my own system and not my co-worker's, with the same `package.json` and the same versions of everything in `node_modules`. Long story short: something depends on the builtin `Buffer`, and my (somewhat old, 8.x from January) copy of Browserify had a bugged version. 

The rest of Browserify's dependency determination system is so explicit and obvious, it completely threw me for a loop to learn that a select set of objects (like `Buffer`) can be populated automatically with whatever happens to be in `node_modules` for Browserify's global installation. 

I can see that this is for compatibility with modules written for node.js, but it's a huge gotcha for this invisible, undeclared dependency to exist between the Browserify version and dependencies of dependencies that one is likely unaware of.

Should builtins need explicit require statements and dependency entries in `package.json`?

P.S: For additional fun: Watchify brings its own version of Browserify with it (with the usual `npm install watchify -g`). If those copies get out of sync, then Browserify and Watchify can build bundles with different versions of the builtins.

**Comment by jmm** [comment]
Hi @PatrickKing. Are you saying that Browserify isn't a dependency in `package.json` and there were different, globally installed, versions on the 2 machines? In any case, Browserify, Watchify, and anything else should be dependencies of the project.

I didn't realize Watchify depends on Browserify -- I guess that's to support the CLI. Seems like a bad idea to me, actually.

**Comment by PatrickKing** [comment]
Yes indeed, Browserify is globally installed on our systems, perhaps that's our mistake. Though, I'll point out that installing Browserify globally is what's done in the readme, I'm surely not the last person who'll follow that example.

**Comment by jmm** [comment]
@PatrickKing Ok, thanks for the feedback. I recommend having your project depend on whatever you need, including Browserify and Watchify, rather than use globally installed modules. It seems to me that there is a general shift toward doing that.

> Though, I'll point out that installing Browserify globally is what's done in the readme, I'm surely not the last person who'll follow that example.

That's a great point. That's probably bad advice at this point. Personally I'm not a fan of using CLIs in general for libraries like Browserify, but the only suitable use case I can think of for using it as a globally installed CLI is for ad hoc operations -- tinkering essentially.

Just today [Babel removed the `preferGlobal` flag](https://github.com/babel/babel/pull/3150) for its CLI (though the docs haven't caught up yet).

I'm going to close the issue because that seems to be the crux of it. If after making those changes there's still a problem, please open a new issue with the details. I'm going to open a new issue about the `README`.

Thanks!
