### ISSUE TITLE
b.bundle: Return readableStream and pass callback? 

### ISSUE THREAD

**Issue by adam-lynch** [substack/node-browserify#1487]
I have a function I use in my gulp setup that looks something like:

```javascript
// browserified - the result of browserify(...)
x = function(browserified, entryScriptPath){
  // Promise is bluebird
  return new Promise(function(resolve, reject){
    var basename = path.basename(entryScriptPath, path.extname(entryScriptPath)) + '.js';
    browserified.bundle()
      .pipe(source(basename)) // vinyl-source-stream
      .pipe(buffer()) // vinyl-buffer
      .pipe(aGulpPlugin())
      .pipe(anotherGulpPlugin())
      //...
      .on('error', reject)
      .on('finish', resolve);
  });
}
````

An error was occurring while bundling but I got no textual error or stackerror, it just exited eventually with the wrong code. So I found this:

>Return a readable stream with the javascript file contents or optionally specify a cb(err, buf) to get the buffered results.

I passed a callback like `browserified.bundle(function(err){ if(err) reject(err); })` which worked fine when there was an error but that now breaks everything else when there isn't an error because the docs say you can either get a stream or a buffer but not both. 

Is there a way I can grab this error another way and still keep my code? Or if not, I know I could move a lot of my stream stuff inside that callback but sorry I'm no stream expert and am unsure how to get that buffer into a vinyl transform stream which suits the gulp plugins. Like:

```javascript
browserified.bundle(function(err, buf){
  if(err) return reject(err);
  
 // ????
 // something with buf
 // ????
 .pipe(aGulpPlugin())
 .pipe(anotherGulpPlugin())
 // ...
});
```

**Comment by MellowMelon** [comment]
Streams are EventEmitters and can spit out [error events](https://nodejs.org/api/stream.html#stream_event_error), which as usual for EventEmitters [crash the process](https://nodejs.org/api/events.html#events_error_events) if not handled. Try attaching the `.on("error", reject)` call to the bundle stream directly:
```js
 browserified.bundle()
    .on("error", reject)
    // ...
```
Your snippet suggests you already have this line elsewhere. But there is no mechanism causing errors to propagate through piped streams, so you need to attach the handler to each stream you might be able to handle errors on. [This mailing list message](https://groups.google.com/d/msg/nodejs/lJYT9hZxFu0/L59CFbqWGyYJ) by isaacs discusses more about this, although I think domains have fallen out of favor since that thread.

**Comment by adam-lynch** [comment]
@MellowMelon great, that sorted it. Thanks :+1:.

It makes sense, I've seen similar issues before with gulp. Thanks, yeah I've definitely a couple of times that domains aren't recommended anymore.
