### ISSUE TITLE
--node doesn't work

### ISSUE THREAD

**Issue by gaurav21r** [substack/node-browserify#1501]
I am using **browserify v13.0.0**

I have an `a.js` which just has a `module.exports = {a: 1}`

And I run browserify as so:
`browserify --node --debug a.js > bundle.js`

In the **node REPL**, 

```
> require ('./bundle.js')
{}
>
```

Why the `{}` ? Shouldn't it give me `{a: 1}`?

Although I've reduced my problem to the simplest case, this behavior is stopping me from bundling a project involving multiple coffeescript files into a single file for node & browsers.

Ive also tried `--bare`, `--no-builtins`, `--no-bf`

**Comment by gaurav21r** [comment]
The same thing works with the **standalone** option. So if I do
`browserify --node --standalone abc --debug a.js > bundle.js`

```
> require ('./bundle.js')
{a: 1}
>
```

Standalone can be `abc` or anything else! It just works

**Comment by gaurav21r** [comment]
@substack @feross @terinjokes Your thoughts?

**Comment by IonicaBizau** [comment]
Any solution to this? Running in the same problem... :disappointed:

**Comment by substack** [comment]
This isn't an issue with `--node`, this is just how browserify works. When you do `browserify a.js` you generate a bundle that will run `a.js`, not export the functionality of `a.js`. You should use `--require` or `--standalone` to generate bundles that will export functionality instead of running when executed.

**Comment by IonicaBizau** [comment]
@substack Using `-s foo` works, but this will generate a global when loaded into a commonjs environment (which in general is not bad). `--require` does not work. It still exports an empty object, like `--node` does.

Basically, the best one is `-s foo` but I don't want to create a global at all, because I know that I will load the module in a Node.js environment. So, what is the option to export functionality but not include the check for commonjs existence?

Thanks! :cake:
