### ISSUE TITLE
Why module's content could be omitted? 

### ISSUE THREAD

**Issue by kuraga** [substack/node-browserify#1549]
Good day!

Very strange (for me) situation:
```js
205:[function(require,module,exports){
(function (process,global,Buffer,__argument0,__argument1,__argument2,__argument3,__filename,__dirname){
var topLevel = typeof global !== 'undefined' ? global :
    typeof window !== 'undefined' ? window : {}
var minDoc = require('min-document');
doccy = topLevel['__GLOBAL_DOCUMENT_CACHE@4'] = minDoc;
module.exports = doccy;
}).call(this,require('_process'),typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {},require("buffer").Buffer,arguments[3],arguments[4],arguments[5],arguments[6],"/node_modules/virtual-dom/node_modules/global/document.js","/node_modules/virtual-dom/node_modules/global")
},{"_process":111,"buffer":104,"min-document":103}]
```

But I don't see contents of `min-document` in bundle! Why could this happen?

Thanks!

**Comment by terinjokes** [comment]
Can you give an example project that fails? What's at module id 103?

**Comment by kuraga** [comment]
@terinjokes thanks for reply!

> Can you give an example project that fails?

https://github.com/kuraga/rotorjs/tree/coverify, `node scripts/test.js > bundle.js` (result: https://gist.github.com/kuraga/eae8452594bb72e13a940f2c69516a39).

> What's at module id 103?

Should be https://github.com/Raynos/min-document. For really, see above.

**Comment by terinjokes** [comment]
`min-document` is required by [`global/document`](https://github.com/Raynos/global/blob/904a038384ee6c3889d550c9721a09260dda4f6b/document.js#L3). It's resolved to an empty module because [`global` says so](https://github.com/Raynos/global/blob/904a038384ee6c3889d550c9721a09260dda4f6b/package.json#L20).

If you're testing in Node.js, you'll want to disable this behavior. If so, you probably want to pass the same options to Browserify that the CLI flag `--node` would. See [bin/args.js](https://github.com/substack/node-browserify/blob/8f7adc96e3ed59c299d078405a463860f5409ba6/bin/args.js#L67-L87).

**Comment by kuraga** [comment]
Wow, thanks! I thought that `--bare` is enough...
