### ISSUE TITLE
take shims out of core

### ISSUE THREAD

**Issue by dominictarr** [substack/node-browserify#1582]
We currently have a difficult breaking change to integrate in crypto-browserify
https://github.com/crypto-browserify/pbkdf2/issues/34#issuecomment-228190327

But a problem is that we don't actually know what modules actually use it, because browserify injects it directly. when node introduces breaking changes, what version does browserify track?
Indeed, since modules do not specify the versions of the core modules they could break unexpectedly with new versions of node. the idea of removing them from core has been kicking around a while, https://github.com/nodejs/node/issues/7098

Removing them from browserify would be much easier, because the browserify shims are already all maintained as separate repos, we'd just have to remove them as deps of browserify... use browserify's already existing config `"browser": {"<core_module>": "<core_module>-browserify"}`

and print a sufficiently helpful error message when a core module is required but not configured.
or possibly it would be okay to automatically resolve `<core_module>-browserify` for the official core modules?

**Comment by substack** [comment]
This could really suck from a user perspective because oftentimes when an upstream package is using a core module, you don't know about it. I don't want to get into the situation that webpack has for example where to use packages you have to know a lot of things about everything you're loading downstream to configure the plugins you use just-so, and when those upstream packages change, your config breaks. I agree that it's better to depend directly on packages with semver, but I don't think browserify should enforce that, to match how node works and to get a high degree of interoperability with the npm ecosystem as it exists currently.

**Comment by terinjokes** [comment]
When these breaking changes happen in Node, it's not uncommon for users to revert for a bit to a previous release. Since pulling in a breaking change in the core shims would be a breaking change for Browserify, the same holds true here. It's annoying, but it's also not without precedence.

The fear I have in this particular case is that users might not immediately know it's breaking their app until later. That might result in some hashes with `binary` and others with `utf8`, and are left with the mess of fixing that.

I agree with @substack in that separating them makes Browserify harder to use for users (since core modules are undeclared in package.json). Even in Webpack, where you have a bunch of plugins and loaders to configure, the core Node.js modules are shimmed automatically, using many of the same shims as Browserify.

**Comment by dominictarr** [comment]
hmm, okay good points. but this does trap us in compatibilty mode.
maybe this should wait until one of the coreless projects makes progress

**Comment by substack** [comment]
One way to make this less sucky is when you see a package on npm that's using core modules and works in the browser, try to get them to switch to specific userland packages.

**Comment by dominictarr** [comment]
yeah, but that would require an annoying pull request bot to do at scale );
