### ISSUE TITLE
Support for lazy loading

### ISSUE THREAD

**Issue by sassanh** [substack/node-browserify#1596]
Is it possible to make `browserify` load modules async? something like `require.async`?

**Comment by goto-bus-stop** [comment]
Yes: https://github.com/arian/partition-bundle

**Comment by sassanh** [comment]
I were able to achieve this using `--external` and `--require` without using `partition-bundle`. The problem with `partition-bundle` was that it was impossible to make some files compile into some specific bundle for any case. Another issue is it's not actively maintained. A combination of `--external`, `--require` and `factor-bundle` works really nice and is totally customizable.

**Comment by niksy** [comment]
@sassanh I was also looking for that and initially started with `partition-bundle`, but quickly found out it missed some important features like dynamic bundle generate process, so I decided to dabble in creating custom transform for that, [browserify-require-async](https://github.com/niksy/browserify-require-async).

First of all, **it’s highly experimental**. It has a lot of moving parts regarding setup since Browserify wasn’t meant to be used like that. I’ve been using it in production projects for some time and it works as expected (no dedicated tests, though).

You could give it a try and see if it works for you!

**Comment by tufandevrim** [comment]
We implemented a browserify plugin for lazy loading called `extractify`
https://github.com/yahoo/extractify
Take look at it and let me know if you need help

**Comment by justinjmoses** [comment]
@tufandevrim how does `extractify` differentiate itself from factor-bundle? (Except that `extractify` is actively under development)

**Comment by sassanh** [comment]
I think community around browserify will benefit a lot from an actively maintained lazy load module but it needs to be really active which means it should fix corner case issues reported by users quickly. extractify as I see in its main page has its latest commit few months ago. No issue submitted yet. I guess it's just in its early phases. I hope in it'll get enough attention and fills the gap in future. I'll try to give it a try in a project and report any issue I find (if any) as soon as I have some free time.
