### ISSUE TITLE
browserify doesn't replace modules correctly

### ISSUE THREAD

**Issue by thinkkevin** [substack/node-browserify#1600]
I wanted to replace `request` module with `browser-request`. However, I found it not working in this scenario.

In my code `index.js`:
~~~~
var aModule = require('a-module');
~~~~

In `a-module`:
~~~~
var request = require('request);
~~~~

When I browserify `index.js`, it will bring huge amounts node.js codes into bundle.

I created an repo to reproduce this problem.
https://github.com/thinkkevin/browserify-issue
All you need to do is to clone and run npm install.

**Comment by brion-fuller** [comment]
I don't think this is an issue with browserify. If you want browser-request you need to import that package and not request.  
```
var request = require('browser-request');
```

**Comment by terinjokes** [comment]
@thinkkevin This works as expected. From the Browserify docs:

> Note that the browser field only applies to files in the local module, and like transforms, it doesn't apply into node_modules directories.

wrapper.js imports "my-module" which imports "request". "my-module" doesn't have a browser field overriding the resolution of "request", so it resolves to the real request module.

"my-module" despite not being in the "node_modules" directory is still a non-local module (with respect to the browser field) because of the presence of the package.json file. The explanation in the docs is a simplification that is correct for 99.9% of cases.
