### ISSUE TITLE
require modules from node_modules folder won't work

### ISSUE THREAD

**Issue by yleclanche** [substack/node-browserify#1619]
Hello,

I build my code with gulp, with this simple task : 

```
gulp.task('js_dev', function () {
    var bundler = browserify({entries: [jsfiles], debug: false});
    //bundler.external('jquery');
    return bundler
        .transform("babelify", {presets: ["es2015"]})
        .bundle()
        .on('error', function (err) {
            console.error(err);
            this.emit('end');
        })
        .pipe(source('theme-dev.js'))
        .pipe(gulp.dest(jsdest));
});
```

When I require module from my own projects, it works.
But when I require modules installed with npm install in node_modules, it does not work and it returns an empty objects.

I tried several modules I used in my projects : babel-polyfill, isotope, slick-carousel-browserify.
Everytime I require them, it returns an empty object. Some modules works.

If you look at the code generated by gulp (http://pastebin.com/TftZfPY7), you can see the code from slick-carousel-browserify is here, but I can't import it.

Any idea what's happening ? 

Thanks.

**Comment by MellowMelon** [comment]
At least two of the modules you've listed try to be compatible with multiple module systems, and they first check the condition `typeof define === "function" && define.amd`. Try typing that into the dev tools console when you load the page. If it's true, it means those modules are deciding you're using AMD/requireJS, and so it doesn't set up the exports browserify is looking for.

**Comment by yleclanche** [comment]
It shows : `{jQuery: true}`, so I guess it's a true.
So what's wrong with my setup ? Why it's using AMD ?

**Comment by MellowMelon** [comment]
Nothing in the bundle you posted sets the define variable, so you need to look at any other script tags your page has other than this bundle.

I'm closing this since browserify's goal is to compile node-style modules, and there's not much it can do if something doesn't assign to exports or module.exports. In the event you do need libraries like slick and isotope to work in browserify even when the AMD module variables exist, you might look at [browserify-shim](https://github.com/thlorenz/browserify-shim).

**Comment by yleclanche** [comment]
Oh my...
My js file were integrated into a CMS which uses AMD.
Thanks a lot for your insight !
