### ISSUE TITLE
Question: Scope of browserified dependencies

### ISSUE THREAD

**Issue by DigitalFlow** [substack/node-browserify#1640]
Hey everyone,

first of all, thanks for this great tool.
I use it for bundling a promise framework (bluebird) with my client script.
It works all well in Firefox, when adding my client script with bundled bluebird.
I'm able to send requests and process the results with .then and .catch handlers without having to reference bluebird from the file that includes my bundled client.
In IE (11) however, I can see that the promises are created properly in my client and even sent, but afterwards I receive an error, that Promise is undefined.
So it seems as if Promise only existed in my client scope and not in the files that use it.

So now I'm wondering, which of those behaviours is the intended one and how can I make sure, that bluebird is available in my client, but also in the files using it, for IE and Firefox?
If it is of any help, [this](https://github.com/DigitalFlow/Xrm-WebApi-Client/blob/master/src/js/WebApiClient.js) is my client.

Thanks for your help.

Kind Regards,
Florian

**Comment by terinjokes** [comment]
In browsers that don't already include a Promise implementation, such as IE, `Promise` will not exist outside the your client file, unless the user imports their own.

Since you're returning a Promise from your functions, users will be able to chain with `.then` and `.catch`, but this won't automatically allow them to create new Promises with `Promise`. They'll have to import a Promise implementation.

**Comment by DigitalFlow** [comment]
Thanks for your answer.
In my test I did not create Promises outside of the client code, I just hooked up to the then and catch functions, but received the errors nonetheless in IE. So in fact it should work to return the promises from my client without having to import bluebird in extern scripts in IE?

Thanks for your help.
