### ISSUE TITLE
Conflict: Two files on the same page with the same required module

### ISSUE THREAD

**Issue by hirasso** [substack/node-browserify#1686]
Hi there! I have a weird issue: I have two files on my HTML-page, both built with browserify and both requiring `TweenLite` from `gsap`. They are completely identical, except animating another DOM-element each. Now the second file that I include in the HTML  always throws an error (see console on the test case). Here's the link:

https://rassohilber.com/debug/tweenlite-browserify/

(open the console to see the error)

**Comment by MellowMelon** [comment]
Looking at the source code, it appears gsap sets up its exports in the global scope while being superficially compatible with browserify. This means that if you include two copies of the library on the page, you'll get strange behavior.

If you have two separate bundles that both need gsap, you probably want to put gsap in a common bundle that both of them use, using browserify's require and external methods. Here's [the basics on that](https://github.com/substack/browserify-handbook#external-bundles), and google can probably give you something on whatever build system you use.

**Comment by hirasso** [comment]
@MellowMelon thanks for your reply! I will post the link to this thread on the gsap forums. Actually, having one bundle file for gsap doesn't work in my case, since I don't control one of the scripts (it's embedded from a remote server).

**Comment by jackdoyle** [comment]
Any chance you could provide more details about what needs to change specifically? GSAP exports both at the global level (many users need that) as well as on the TweenMax object itself (what gets returned by importing "gsap"). Seems to work fine in other build systems as well as in Browserify...except in this case where it's required multiple times. As far as I know, that's only an issue in Browserify, not other packagers. If you're saying it's a problem with GSAP, it'd be great to hear more details and suggestions. Thanks :)

**Comment by MellowMelon** [comment]
Browserify's job is to allow Javascript written assuming a node environment to run inside of a browser within certain constraints. So it provides things like a `module` and `exports` variable inside each file. The job of GSAP's UMD lines, which can be seen in the built bundles above, is to sort through which of these module variables exist and use that provide the exports in the format the user is expecting. The issue here is that those UMD lines are doing something strange when the GSAP code is included in the page twice and the variables Browserify provides are in place.

When a library is messing with globals like this, I would treat including it on a page twice as undefined behavior. The authors of libraries that are intended for browsers generally don't do anything to account for a library being included twice, because in browsers the goal is often to cut down on how much Javascript you're including. Behaving correctly when included twice would be a very strange thing to support.

And in fact, I have in the past run into subtle issues where a library (Handlebars in my case) was accidentally included on a page twice and everything worked for months until an edge case came up. (That was a miserable bug hunt.) So when you say it's not an issue in other packagers, it probably means you're getting lucky with the undefined behavior and/or you haven't seen it break yet.

If I had to work with constraints forcing the library to be on the page twice, personally I would start seriously considering hacks. Something like getting script tags in between the two libraries and trying to clean up all the global state that is causing the second library to throw errors.
