### ISSUE TITLE
Unneeded dependencies pulled in for dependencies with`browser` property

### ISSUE THREAD

**Issue by silverwind** [substack/node-browserify#1687]
[public-ip](https://github.com/sindresorhus/public-ip) has a `browser` property in package.json which points to [browser.js](https://github.com/sindresorhus/public-ip/blob/master/browser.js), which currently only includes the `is-ip` dependency. browserifying that give a lightweight package:

````sh
$ browserify browser.js | wc -c
    3355
````

But if one creates another project that depends on the `public-ip` package, the `got` dependency which is not actually used in `browser.js` (only in `index.js`) is needlessly included:

```sh
$ browserify my-project.js | wc -c
  287709
```

**Comment by substack** [comment]
There is no file `browser.js` in `public-ip`:

```
$ npm i public-ip
$ ls node_modules/public-ip/
index.js  license  package.json  readme.md
```

I think this file is not found so browserify falls back to using the index.js. This is because package.json includes a "files" property that excludes browser.js:

```
$ json files < node_modules/public-ip/package.json 
[
  "index.js"
]
```

The "files" property in package.json is not something that I use for this reason, but it seems like browserify is behaving as it should here.
