### ISSUE TITLE
Implement module.parent so Socket.io can work

### ISSUE THREAD

**Issue by edmellum** [substack/node-browserify#41]
Socket.io doesn't work right now because it uses module.parent.

Would it be possible to implement module.parent in Browserify?

**Comment by impinball** [comment]
@rattrayalex You'll run into larger issues, simply because of their [Contextify](https://www.npmjs.com/package/contextify) dependency, which contains about [350 lines of C++](https://github.com/brianmcd/contextify/blob/master/src/contextify.cc) for creating a new V8 context to run code in. Good luck.

**Comment by dhruvio** [comment]
+1

**Comment by impinball** [comment]
Warning: this would be near impossible without runtime boilerplate, and lots of it. Where Browserify statically compiles the requires down to a single file, much of the filename information is lost, and the current module is largely unknown at runtime. Sourcemaps only know about them because they are only built to deal with line-to-line mappings, and can translate those mappings across files. On the other hand, those mappings are also statically generated, and cannot be retrieved during runtime.

Consider this:

```js
// a.js
require('./b');
require('./c');

// b.js
var parent = require('./d');
process.nextTick(function () {
  console.log(parent());
});

// c.js
var parent = require('./d');
process.nextTick(function () {
  console.log(parent());
});

// d.js
module.exports = function (x) {
  return module.parent;
};
```

You would have to do some serious code analysis along with some actual evaluation to be able to tell what `module.parent` is. This is harder to accomplish than [this](https://github.com/mishoo/UglifyJS2/issues/205) (see [my comment](https://github.com/mishoo/UglifyJS2/issues/205#issuecomment-71357459) explaining why it's so difficult).

You want a harder example? Then look at this:

```js
module.exports = function () {
  var mod = path.resolve(SOURCE_ROOT, module.parent.filename);
  console.log('Log from ' + mod + ': ');
  console.log('`this`: ' + this);
  console.log('Arguments:');
  for (var i = 0; i < arguments.length; i++) {
    console.log('  ' + i + ': ' + arguments[i]);
  }
  console.log();
};
```

It may look rather simple, but there is no safe way to bake in `module.parent` regardless of call site, since it is dynamically generated by Node.js. It's practically impossible to implement this safely without a implementation for each call of this function, given it is dependent on every way you could think of silently baking in an extra parameter for the function.

**Comment by alice0meta** [comment]
It would still help to make it non-falsey, so that scripts using `if (!module.parent)` as their `main` switch don't run their `main`.
