### ISSUE TITLE
Allow transforms to be configured with options

### ISSUE THREAD

**Issue by colinkahn** [substack/node-browserify#546]
I've been messing around with my own transforms and see a lot of potential for them to replace certain grunt tasks I have, but I'd need to be able to pass them additional options.

I originally tweeted something along the lines of this on twitter and @substack replied saying currently the best way is using environment variables: https://twitter.com/substack/statuses/410566575117185024

I imagine them too look something like this: 

```
browserify: {
  transforms: [
    "coffeeify",
    {name: "ngtemplateify", module: "mod"}
  ]
}
```

Also regarding transforms, perhaps it would be good to be able to turn off module level transforms from these options, for example, lets say I'm using some special transforms that are in my karma config:

```
browserify: {
  transforms: [
    {name: "coffeeify", disable: true},
    // not a published transform yet, but would use Ibrik to add 
    // coverage and at the same time convert coffee files to javascript
    {name: "ibrikify"} 
  ]
}
```

In that case, if I had a module level transform specifying "coffeeify", my "ibrikify" transform would already have converted the coffee files to js and when the module level transform was applied it would throw an error. So, this would solve that problem without having to expose something like `transformKey` as a browserify option to be able to set it to `false` ignoring all module level transforms.

**Comment by andrewvaughan** [comment]
Read this.  Still very confused - I'd very much like to configure transforms in my initialization of browserify in my code, but find no examples (using third party tools) on how to do so anywhere.

**Comment by jwalton** [comment]
The "configuring transforms" landscape has changed quite a bit since this conversation took place.  From [the README](https://github.com/browserify/browserify#btransformtr-opts):

>Transforms may obtain options from the command-line with subarg syntax:
>
>```sh
>$ browserify -t [ foo --bar=555 ] main.js
>```
>
>or from the api:
>
>```js
>b.transform('foo', { bar: 555 })
>```

If you're writing a transform, (it's been a while since I did this so I might have this wrong) I'm pretty sure it's just a `function transform(file, config) {...}`.  This seems to be where my [browserify-transform-tools](https://github.com/benbria/browserify-transform-tools/blob/66497a5171ad8b5ce3a5ab6907dbde5755804f3e/src/transformTools.coffee#L66) library gets it from.  :P
