### ISSUE TITLE
Feature request: Avoid loading linked modules multiple times

### ISSUE THREAD

**Issue by mantoni** [substack/node-browserify#692]
We run into the following issue with quite a large dependency tree:

When linking packages with `npm link` that share a dependency, Browserify loads the module twice because they are in different paths. This leads to various problems from multiple socket connections to `instanceof` not working anymore.

It would be great if Browserify could consider the package.json's name / version to detect this case.

Thanks!

**Comment by madcapnmckay** [comment]
@substack @mantoni - I think this bug may still be around. I had two versions of a common module being included even though it was the same version. I did a diff of the two directories and they actually differed because package.json has a _from property that denotes the version range that caused that module to be included. Because the deps were being included with a slightly different carart include i.e. ^1.3.2 & ^1.3.1 respectively, the _from field was different even though the actual module contents was identical.

Even after I fixed that issue and my manual diff passed two instances were still included.

Needless to say this is super brittle. Out of interest why can't browserify be version aware? Wouldn't that solve these issues and avoid having to do hash comparisons?

**Comment by substack** [comment]
browserify doesn't look at the package.json version field at all. If the file contents are different, browserify will include both versions. If the contents are identical, only one version is included.

Browserify doesn't look at the version field because it's unreliable. A package can have whatever value it wants for the version fields, but the contents of files may still differ. This is common if you're working on a package locally and haven't published an updated version to npm.

I recommend using `npm dedupe` to fix these issues or install npm v3: `npm install -g npm@^3`, which dedupes by default.

**Comment by pmowrer** [comment]
@madcapnmckay You may want to try [browserify-resolutions](https://github.com/Updater/browserify-resolutions). It's a plugin to Browserify that more aggressively dedupes

**Comment by saiichihashimoto** [comment]
I've run into this same issue. In my case, the dependency looks more like:
```
  B
   \
B   C
 \ /
  D
```
where D is the application bundle, B is underscore, and D is npm linking C. In my case, when C requires B, it throws an error:
```
Uncaught TypeError: Cannot read property '0' of undefined
```
What I'm requiring also is going through the [jstify](https://github.com/zertosh/jstify) transform, which may be part of the issue? Regardless, to deal with this, in both C & D I ```npm link B```. Then they happily use the same version.

This is... poor. Especially if there's more than one dependency that they share. This shouldn't be a manual fix like this.

**Comment by hugomallet** [comment]
Hi,

Is there a fix planned for this issue?
Or is there a preferred development practice to dedupe dependencies of linked modules?

**Comment by ericsoco** [comment]
Finally found a reusable solution to the problem of duplicated deps when `npm link`ing, and it's not specific to any build tool:
http://stackoverflow.com/a/36464203/222356

Curious to hear your thoughts.

**Comment by oztune** [comment]
I found the solution @ericsoco suggested to work perfectly without requiring any project changes.

For future readers, to make this fit into our existing workflow I put together a node module you may find useful and save you some keystrokes: https://github.com/oztune/gn
