### ISSUE TITLE
Browserify output is not always the same, even from the same machine

### ISSUE THREAD

**Issue by boblauer** [substack/node-browserify#711]
I created a simple project and readme at https://github.com/boblauer/BrowserifyExample so anyone can reproduce the issue.  A large percent of the time, Browserify spits out the same file, but occasionally the order of the the bundle's entries will be different.  I tried to figure out what was going on myself, but I was getting nowhere fast.

**Comment by Kureev** [comment]
Eventually, we experience this issue in `browserify@12.0.2`. Any ideas why? Running browserify twice with the same input gives us different output.

**Comment by Moonshell** [comment]
I've met this problem recently.
The results of bundling task, are always different between my machine and my partner's. Although we are both using Windows system.
And when we commit our generated code to SVN before publish our website online. To check if the generated code has changed is impossible, because of the different module order.
We are using `browserify@13.0.1`.
